const TierList = {
    'X+': [
        'Aegir, the Roaring Sea II',
        'Crassus, the Lion General II',
        'Hel, Goddess of Woe II',
        'Lancelot of the Lake II',
        'Ortlinde, Silent Valkyrie II',
        'Poliahu, the Mauna Kea',
        'Sabnock, Marquis of Hell II',
        'Thanatos, Death Incarnate II',
        'Van, Shadow Hunter II',
        'Zepar, Blood-Annointed II'
    ],
    X: [
        'A\'shi, Pterorider II',
        'Adranus, Lava Beast II',
        'Amaterasu, Light of the Sun II',
        'Amethyst Dragon II',
        'Andras, the Slayer II',
        'Arcanan Death II',
        'Arcanan Fool II',
        'Arcanan Star II',
        'Arcanan Sun II',
        'Arcanan Temperance II',
        'Arcanan Terra II',
        'Ares, God of Ruin II',
        'Aspidochelone, the Iceberg II',
        'Ausra, the Fall Breeze II',
        'Azazel, the Temptress II',
        'Azi Dahaka II',
        'Banshee Rider II',
        'Bastet, Cat Goddess',
        'Beatrice, the Luminescent II',
        'Beelzebub, Glutton King II',
        'Belle, Grimoire Keeper II',
        'Brine Drake',
        'Camazo, Knight of Bats II',
        'Champion of Aquarius II',
        'Chicomecoatl, the Bountiful II',
        'Dauntless Justice',
        'Dionysus, the Reveler',
        'Emerald Dragon II',
        'Fafnir, Fireclad Dragon II',
        'Fenrir, Vengeful Beast',
        'Garshasp, the Juggernaut',
        'Gorynich, Snow Dragon II',
        'Gunhild, Brass Pincers II',
        'Guillaume, Fanatic',
        'He Qiong, the Transcendent II',
        'Helen, Swan Queen II',
        'Heracles, Mightiest of Men II',
        'Horus, the Falcon God II',
        'Huitzilopochtli, God of War II',
        'Idun, the Golden Apple II',
        'Ixtab, Guardian of the Dead II',
        'Intrepid Hand of Mercury',
        'Isabella, the Waterbrand',
        'Kaikias, the Hail God',
        'Ker, the Despair Diamond',
        'Kokopelli Mana II',
        'Kokuanten, the Ominous II',
        'Kushinada, Shamaness II',
        'Lady Tatsuta, the Mapleleaf II',
        'Laned, the Piercing Fist II',
        'Laola, Demiwyrm Spearbearer II',
        'Lippy, Candymancer II',
        'Liza, Blood-Anointed',
        'Lu Bu, the Peerless',
        'Maisie, Grimoire Keeper II',
        'Maleficent Chimaera II',
        'Medb, Jealous Queen II',
        'Menelaus, Vengeful King',
        'Michael, Steelclad Angel II',
        'Mormo, Nightmare II',
        'Nidhogg, Iceclad Dragon II',
        'Nike, Goddess of Victory II',
        'Odoa, the Scarecrow II',
        'Oenone, the Hailstorm',
        'Pallas, Goddess of Protection II',
        'Peri, Spirit of Fire II',
        'Persephone, Spring Goddess  II',
        'Pomona, Grove Goddess II',
        'Qing Nu, Snowweaver II',
        'Rapunzel, Grimoire Keeper II',
        'Rattlebolt Wyvern',
        'Renenet, Goddess of Wealth',
        'Scathach, Shadow Goddess II',
        'Shackled Red Wyrm II',
        'Silver Dragon II',
        'Sir Galahad, Knight Champion II',
        'Sir Gawain, Sun Knight II',
        'Skeleton King II',
        'Snegurochka II',
        'Spartacus, Rebel Gladiator II',
        'Strigoi, Undying Warrior II',
        'Triton, Lord of the Sea II',
        'Tyr, God of War II',
        'Ulfhe, Sword-Shield Master II',
        'Urom, Mummy Lizardman II',
        'Vidar, the Iron Heel II',
        'Virginal, Ice Queen',
        'Vlad, Swap II',
        'Walutahanga, Guardian Dragon',
        'Wrath, Beast of Sin II',
        'Zeruel Angel of War, Swap',
        'Zhu Rong, the Blazing Storm'
    ],
    'S+': [
        'Ah Puch, Lord of Death',
        'Alyssa, Black Cat Witch II',
        'Aletheia, Knight Templar II',
        'Ammit, Soul Destroyer II',
        'Amphion, Hymn of Death',
        'Amphisbaena II',
        'Ankou, Harbinger of Death II',
        'Anneberg, Steel Steed II',
        'Apate, Goddess of Deceit',
        'Apep the Chaotic',
        'Apollo, God of the Sun II',
        'Apsara, Spirit of Water II',
        'Arcanan Circle of Fate',
        'Arcanan Daemon II',
        'Arcanan Emperor II',
        'Arcanan Empress II',
        'Arcanan Hanged Man II',
        'Arcanan Hermit II',
        'Arcanan High Priestess II',
        'Arcanan Judgment II',
        'Arcanan Lovers II',
        'Arcanan Moon II',
        'Arcanan Might II',
        'Ashlee Steamsaw II',
        'Aso, the Asura',
        'Baba Yaga II',
        'Bandersnatch, Beast Divine II',
        'Befana, the Moonless Night',
        'Belial, Lord of Vices',
        'Benjamina, Wild Turkey',
        'Bercilak, Green Knight II',
        'Bijan, the Comet',
        'Blazing Drake',
        'Brass Rabbit',
        'Briar, Grimoire Keeper II',
        'Caassimolar, the Chimera II',
        'Calais, the Gale II',
        'Captain Jed II',
        'Captain Kidd II',
        'Chanchu, Hermit II',
        'Crystallus Rex II',
        'Cu Chulainn, the Thunderbolt',
        'Cursebone Pterosaur II',
        'Dagon II',
        'Diana, the Crescent Moon',
        'Danniel, Golden Paladin II',
        'Darkwind Wyvern',
        'Decaying Dragon',
        'Demonblade Countess',
        'Discordia, Bringer of Ruin',
        'Djinn of the Lamp II',
        'Dryas, Centaur Knight II',
        'Elsa, Undead Bride II',
        'Empusa, the Death Scythe',
        'Erupting Golem',
        'Etain, Scalewing Faerie II',
        'Feathered Drake',
        'Fell Bonedrake Knight',
        'Ferocious Siege Tower',
        'Frost Bearwolf II',
        'Gabrielle, Angel of Sky II',
        'Galatea, Nereid II',
        'Gargoyle Gatekeeper II',
        'Garmr, Watchhound II',
        'Ghislandi, the Unchained II',
        'Gigantopithecus II',
        'Gilgamesh the Bold II',
        'Goliath, Titanic Warden',
        'Gremory, the Vermilion Moon',
        'Gryla, Swap II',
        'Guardian of the Grove II',
        'Hei Long, the New Moon',
        'Hel, Goddess of Death II',
        'Hellscale Theropod',
        'Hippocamp II',
        'Hippolyta, Amazon Queen II',
        'Hollofernyiges II',
        'Hypnos, Lord of Dreams II',
        'Ijiraq the Brinicle II',
        'Impregnable Iron Golem',
        'Infernal Wyrm Warden',
        'Intrepid Hand of Jupiter',
        'Intrepid Hand of Neptune',
        'Intrepid Hand of Uranus',
        'Intrepid Hand of Venus',
        'Jabberwock, Phantom Dragon II',
        'Jarilo, God of Fertility',
        'Julia, Centaur Eques II',
        'Juno, Goddess of Affection II',
        'Kapoonis, Thunder Magus II',
        'Karna, the Red Eye II',
        'Kibitsuhiko, Ogre Slayer II',
        'Kotyangwuti, Spider Spirit II',
        'Lachesis, the Measurer II',
        'Lamashtu, Fell Goddess',
        'Lava Dragon II',
        'Long Nu, Sea Princess',
        'Lucan, Eagle Knight II',
        'Lucifuge, Infernal Premier',
        'Luot, Scout II',
        'Magdal, Dragonmaster II',
        'Managarmr, the Frost Moon II',
        'Manannan mac Lir II',
        'Mammi, Hare of the Harvest II',
        'Marraco, Crusted Wyrm II',
        'Melek, the Black Peacock II',
        'Microraptor II',
        'Mielikki, Bear Rider II',
        'Millarca, Lady of Thorns II',
        'Muramasa, the Cursed Katana II',
        'Musashi, the Twinblade II',
        'Neith, Goddess of War II',
        'Nephthys, Ruler of Death',
        'Nimue, Lady of the Lake II',
        'Niu Mo Wang II',
        'Odin, God of Victory II',
        'Oscar the Green II',
        'Ovinnik, Hex Beast II',
        'Paladin of Ophiuchus II',
        'Paladin of Taurus II',
        'Pasiphae, the Brass Bull II',
        'Pegasus Knight II',
        'Pele, Volcano Shamaness II',
        'Perendon the Pure',
        'Phantasmal Succubus II',
        'Pontifex Antiquus II',
        'Prismatic Wyvern',
        'Queen of the Waspmen II',
        'Qiong Qi, World Eater II',
        'Raging Cetus',
        'Rampant Lion II',
        'Ravaging Hafgufa II',
        'Ritho, King of the Giants II',
        'Rongo, Moai Master II',
        'Rusalka, Spirit of Water II',
        'Ryaum, Hussar Captain II',
        'Sachiel, Angel of Water II',
        'Sagacious Treant II',
        'Phantom Knight, the Vagabond II',
        'Saizo, Phantom Ninja II',
        'Samedi, Dark Necromancer II',
        'Samhain, Night Trampler',
        'Scirocco, Father of Winds II',
        'Sea Serpent II',
        'Sedna, the Frozen Sea II',
        'Seimei, Onmyoji II',
        'Sigurd, Dragonslayer II',
        'Sigiled Corpse Beast II',
        'Skadi, Goddess of Winter',
        'Srak, Exorcist II',
        'Susanoo, Rowdy God II',
        'Svadilfari II',
        'Takemikazuchi, the Lightning II',
        'Tanba, Founder of the Ninja II',
        'Tangata Manu, Withering Gale',
        'Tannin, Sea Dragon II',
        'Thor, the Roaring Thunder',
        'Tricia, Cauldron Witch II',
        'Twar, the Moonlit Night II',
        'Tyche, Goddess of Glory',
        'Uscias, the Claiomh Solais II',
        'Ullr, Starshooter II',
        'Urcagu, the Grinder',
        'Vesta, Flame Witch II',
        'Vlad the Impaler II',
        'Waheela, Dire Wolf II',
        'Waltraute, Valiant Valkyrie II',
        'War Bear II',
        'Xuan Wu II',
        'Ymir, Primordial Giant II',
        'Zahhak, Dragon Marshal II',
        'Zaphkiel, the Blessed Rain',
        'Zeruel, Angel of War II',
        'Zuniga, Guard Captain II'
    ],
    S: [
        'Acanthus, the Gilded Thorn II',
        'Achilles, Fallen Hero II',
        'Aengus, the Charitable II',
        'Afanc, Beast of the Deep II',
        'Agate, Gem Tamer II',
        'Aipaloovik, Sacred Dragon II',
        'Ales Darkblood II',
        'Alluring Merrow II',
        'All-Seeing Keeper II',
        'Andromalius, Eater of Lies II',
        'Anubis, Keeper of the Dead II',
        'Apocalyptic Beast II',
        'Arcanan Chariot II',
        'Arcanan Magus II',
        'Archbishop of the Deep II',
        'Archduke Ose II',
        'Atalanta, Fowler II',
        'Baal, Thunder Lord of Hell II',
        'Bai Suzhen, Lady of Scales II',
        'Bella, the Dazzling Flower II',
        'Bergel, Frost Magus II',
        'Bheara, Wastestrider II',
        'Botis, Dasher of Hopes II',
        'Brang Two-Heads II',
        'Caim, Death Seeker II',
        'Canhel, Guardian Dragon II',
        'Cap\'n Jolly, Sea Scourge II',
        'Carl, Giant Knight II',
        'Cat Sith Magus Master II',
        'Cat Sith Warlord II',
        'Cat Sith Whipmaster II',
        'Chariot Hippocamp II',
        'Chuchunya, Tundra Guardian II',
        'Chione, Fallen Heroine II',
        'Circe, Fallen Heroine II',
        'Clockwork Pumpkin II',
        'Clockwork Viper II',
        'Cocytus Dragon II',
        'Cyclops, the Rocky Cliff II',
        'Danzo, Falcon Ninja II',
        'Dasher, Battle Reindeer II',
        'Deimos, Terror Spear II',
        'Domini, Pest Controller II',
        'Doppeladler II',
        'Europa, Fallen Heroine II',
        'Etain, Butterfly Tamer II',
        'Fenghuang, Bird Divine II',
        'Fenrir II',
        'Freyr, God of the Harvest II',
        'Gathgoic the Other II',
        'Gevi, Crystal Troll Master II',
        'Grigo, Hobgoblin Slicer II',
        'Gryla, the Lullaby II',
        'Hagen, Dueling King II',
        'Hash, Lizardman Cannoneer II',
        'Hatshepsut, Mummy Queen II',
        'Heinrich the Bold II',
        'Hellawes, Fetter Witch II',
        'Hermine, High Priestess II',
        'Hina, Flame Serpent II',
        'Hlokk, Blade of Thunder II',
        'Hoska, the Firestroke II',
        'Hundred-eyed Warrior II',
        'Icarus, Fallen Hero II',
        'Infested Cyclops II',
        'Ishtar, Goddess of Love II',
        'Jack o\' Frost II',
        'Joro-gumo II',
        'Kalevan, Swap II',
        'Kekro, Demiwyrm Magus II',
        'Koroku, the Death Stinger II',
        'Kosuke, Master Ninja II',
        'Lenore, the Sly Fox II',
        'Loki, God of Cunning',
        'Madprowl Lynx II',
        'Magdal Dragonheart II',
        'Malebranche, the Chimera II',
        'Marchosias, Pit Beast II',
        'Medea, Vengeful Queen II',
        'Midas, the Wailing King II',
        'Minerva, Goddess of War II',
        'Minos, Judgment King II',
        'Mizuchi, the Raging Storm II',
        'Moloch, Soul Reaper II',
        'Momoso, Pheasant Tamer II',
        'Muspell, Giant Knight II',
        'Negafok, Reindeer Rider II',
        'Nicola, the Poison Fly II',
        'Nyx, the Dark Wing II',
        'Olan, Tricky Succubus II',
        'Ollpheist II',
        'Oka, Kunoichi II',
        'Okypete, the Swiftwing II',
        'Pagos, Camel Cavalryman II',
        'Pakal, Jade King II',
        'Pandora, Fallen Heroine II',
        'Paladin of Aquarius II',
        'Paladin of Cancer II',
        'Paladin of Gemini II',
        'Paladin of Leo II',
        'Paladin of Sagittarius II',
        'Paladin of Scorpio II',
        'Paladin of Virgo II',
        'Paris, Trueshot II',
        'Peg Powler II',
        'Pelops, Fallen Hero II',
        'Peony, the Jiang Shi II',
        'Petsuchos Minister II',
        'Phlox, Avern Witch II',
        'Premyslid, the Black King II',
        'Ragnelle, the Moonlight II',
        'Rovn, the Brass Panzer II',
        'Scathing Hierophant',
        'Scorching Marid II',
        'Seismo Worm',
        'Set, God of the Sands II',
        'Sinbad the Adventurer II',
        'Sir Brandiles, the Flameblade II',
        'Sir Oliver, the Golden Sword II',
        'Stalo, Glacial Giant II',
        'Sugaar, the Thunderstorm II',
        'Takshaka, Serpent King II',
        'Telluric Drake II',
        'Thunderbird II',
        'Tiamat, Mother of Dragons II',
        'Thoth, Hieroglypher II',
        'Tormented Bone Beast II',
        'Vepar, the Roiling Sea II',
        'Vezat, Dragonbone Warrior II',
        'Vivian Griffinrider II',
        'Void Yaksha II',
        'Vucub Caquix, the Barbarian II',
        'Wang Yi, Lady of Iron II',
        'Wicker Man II',
        'Wolfert, Grave Keeper II',
        'Wyrm Warden, Everwakeful II',
        'Wyvern Gemwarden II',
        'Yae, the Night Flower II'
    ],
    'A+': [
        'Abyssal Rahab II',
        'Aeneas, Fallen Hero II',
        'Aeshma, the Tyrant II',
        'Adara Luck Shot II',
        'Adara Luck Shot, Swap II',
        'Agathos, Wyrm of the Harvest II',
        'Ain, Squirrel-back Faerie II',
        'Aipaloovik, the Snowstorm II',
        'Alberich, the Ceratophrys II',
        'Alcina the Soulsucker II',
        'Allocer, Great Duke of Hell II',
        'Alp, Dynast of Darkness II',
        'Amazon Berserker II',
        'Ame no Uzume, the Lure II',
        'Ancient Beetle Soldier II',
        'Ancient Tree Golem II',
        'Antaeus, Giant II',
        'Asena, Wolfwoman II',
        'Aslaug, the Lyre Bow II',
        'Autolycus, Shrewd Warrior II',
        'Azan, the Dragon Bone II',
        'Badalisc, the Gourmet II',
        'Bayam II',
        'Belisama, Flame Goddess II',
        'Brangane, the Enchanting II',
        'Brass Tarantula II',
        'Bronzeclad Hyena II',
        'Caparisoned Barometz II',
        'Cat Sith Swordswoman II',
        'Cegila, Dragonian Incantator II',
        'Charon, Greedy Ferryman II',
        'Charybdis II',
        'Chi-Hu II',
        'Crystalwing Roc II',
        'Delphyne, Thunder Dragon II',
        'Dong, the Bloody Claw II',
        'Druj Nasu, the Impure II',
        'Dryad Archer II',
        'Dunkleosteus, the Rendmaw II',
        'Ebon Dragon II',
        'Eric, Bloodaxe King II',
        'Eros, the Golden Arrow II',
        'Ettin II',
        'Feng, Sanjiegun Master II',
        'Fergus, Bold King II',
        'Flame Dragon II',
        'Fleetfoot Ornithomimus II',
        'Figgo, Executioner II',
        'Freyja, Earth Goddess II',
        'Frostscale Plesiosaur II',
        'Garuda II',
        'Ghost Carriage Express II',
        'Gilles, Mad Knight II',
        'Gog, Giant II',
        'Halphas, Earl of Hell II',
        'Haokah, the Lightning Brave II',
        'Hati, Icetail Wolf II',
        'Hecatoncheir Rimetouch II',
        'Hecatoncheir the Adamantine II',
        'Hippogriff of Rites II',
        'Hraesvelg, Corpse Feaster II',
        'Hercinia the Blest II',
        'Infested Minotaur II',
        'Inhabited Ghost Ship II',
        'Ira, Hypnotic Specter II',
        'Iridescent Chalchiuhtotolin II',
        'Ivy the Verdant II',
        'Jarn, the Bladed Wolf II',
        'Jason, Fallen Hero II',
        'Jinx-eye Dragon II',
        'Jormungandr, World Serpent II',
        'Kagemaru, Master Ninja II',
        'Kalevan, the Forest Green II',
        'Kangana, the Maelstrom II',
        'Kua Fu, Sun Chaser II',
        'Kyteler the Corrupted II',
        'Leupold, Wyvern Knight II',
        'Linnorm, the Hailstorm II',
        'Ljung, the Wrecker II',
        'Long Feng, the Dragon Fist II',
        'Louise, Twilight Swordswoman II',
        'Lubberkin, Four Leaf Clover II',
        'Magog, Giant II',
        'Mammon, Raven Claw II',
        'Marcus, Brave of Liberation II',
        'Marsyas, the Cursed Flute II',
        'Mathilda the Tarantula II',
        'Melanippe, Wolfrider II',
        'Moni the Dismemberer II',
        'Montu, God of War II',
        'Najeeba, the Mapleblade II',
        'Narmer, Mummy King II',
        'Nehasim the Seething II',
        'Nergal, Abyssal Overseer II',
        'Nin-Ridu',
        'Olitiau, the Great Bat II',
        'Orpheus, Fallen Hero II',
        'Paladin of Aries II',
        'Paladin of Capricorn II',
        'Paladin of Pisces II',
        'Palamedes, the Hawk\'s Eye II',
        'Pazuzu, the Whirling Jinn II',
        'Phoenix, the Metempsychosis II',
        'Pixiu, the Wealthy II',
        'Pollux, Fallen Hero II',
        'Pumpkin Hangman II',
        'Ragnar, Dragonslayer II',
        'Rapse, the Bloody Horns II',
        'Reinforced Gem Golem II',
        'Ruprecht the Punisher II',
        'Rustom, Zombie Ape II',
        'Ruyi Zhenxian, the Ferocious II',
        'Sasquatch Sweet Tooth II',
        'Selkie, Lady of the Shore II',
        'Sera, Exorcist II',
        'Siby, Sea Seer II',
        'Sigiled Skeleton Axeman II',
        'Sihn, Moonlight King II',
        'Shisen, the Flitting Bolt II',
        'Simurgh, Bird Divine II',
        'Skoll, Dark Wolf II',
        'Skrimsl the Freezing II',
        'Snow Queen II',
        'Soura, Inferno Shaman II',
        'Suan Ni II',
        'Surtr the Fervent II',
        'Taromaiti, Fallen Goddess II',
        'Thundering Pterosaur II',
        'Tomoe, the Lightning Arrow II',
        'Tristan the Sorrowful II',
        'Typhon II',
        'Vafthruthnir, Elder Giant II',
        'Valin the Terrible II',
        'Vengeful Siege Horse II',
        'Venusia, the Grace II',
        'Wepwawet, the Vanguard II',
        'Xaphan, the Foul Flame II',
        'Yule Goat, Death Bringer II'
    ],
    A: [
        'Anne, the Whirlwind II',
        'Amon, Marquis of Blaze II',
        'Astaroth, Duke of Fear II',
        'Aurboda, the Great Mother II',
        'Ausguss, Jailer II',
        'Balgo, the Cursed Flame II',
        'Batraz, the Immortal Hero II',
        'Bennu, the Sun Bird II',
        'Cat Sith Chillweaver II',
        'Cuelebre the Ironscaled II',
        'Dagr Sunrider II',
        'Dein, Silent Bomber II',
        'Desna, Mythic Wendigo II',
        'Dharva Fangclad II',
        'Dors, Demiwyrm Warrior II',
        'Edgardo, Grand Inquisitor II',
        'Eton, Eater of Darkness II',
        'Flesh Collector Golem II',
        'Gaiuz, Crashing Wave II',
        'Gorlin Gold Helm II',
        'Grandor, Giant of Old II',
        'Gregory, the Masked Slayer II',
        'Grellas Fellstaff II',
        'Griffin Mount II',
        'Hamad, the Sweeping Wind II',
        'Hereward, Storm of Arrows II',
        'Huan, Doomcaller II',
        'Ijiraq, the Glacier II',
        'Ioskeha',
        'Iseult the Redeemer II',
        'Jack, the Rusty II',
        'Khepri, the Morning Sun II',
        'Kijin, Heavenly Maiden II',
        'Kobold Guard Captain II',
        'Lahamu, Royal Viper II',
        'Lanvall, Lizard Cavalier II',
        'Latona, Wolfwoman II',
        'Lucia, Petal-Shears II',
        'Managarmr Frost Touch II',
        'Mauthe Doog II',
        'Nightblade, Archsage of Winds II',
        'Odin Stormgod II',
        'Onra, Ogre Lord II',
        'Oniroku the Slayer II',
        'Paladin of Libra II',
        'Palna, the Vanguard II',
        'Ramiel, Angel of the Storm II',
        'Rasiel, Angel All-Knowing II',
        'Reinforced Brass Gorilla II',
        'Regin, the Brass Mantis II',
        'Rohde, the Rose Thorn II',
        'Saurva, the Lawless Lord II',
        'Sekhmet Aflame II',
        'Selk, Desert King II',
        'Solsten the Really Wanted II',
        'Spellforged Cyclops II',
        'Taotie, the Gluttonous II',
        'Tawiscara',
        'Veigr, Under-watch Captain II',
        'Venomhorn Karkadann II',
        'Zagan II'
    ],
    B: [
        'Agathos, the Ruinous II',
        'Andorra the Indomitable II',
        'Behemoth, Thunder Beast II',
        'Bert, Foe Sweep II',
        'Biast II',
        'Black Knight, Soul Hunter II',
        'Bolus, the Blue Bolt II',
        'Borivoi, the Black Prince II',
        'Botis, Earl of Hell II',
        'Brass Snow-Leopard II',
        'Bunga, the Stalwart II',
        'Camael, Angel of Destruction II',
        'Cassandra, the Tragic II',
        'Cernunnos II',
        'Charon, Darksun Ferryman II',
        'Chaotic Magma Giant II',
        'Chiyome, the Kamaitachi II',
        'Chuchunya, Iceberg Breaker II',
        'Crystal Gillant II',
        'Dantalion, Duke of Hell II',
        'Dark-Imbued Siege Horse II',
        'Deborah, Knight Immaculate II',
        'Denki the Raven II',
        'Dire Bat Pegasus II',
        'Douma, Bonze of the Dark II',
        'Farwal the Glutton II',
        'Evil Eye II',
        'Fiendish Bat Demon II',
        'Fimbul Frostclad II',
        'Figgo, Torturer II',
        'Fionn, the Meteor Sword II',
        'Fomor the Savage II',
        'Freila the Bountiful II',
        'Gangaruda the Destroyer II',
        'Ghislandi, Iron Heart II',
        'Gilbert, Moth Handler II',
        'Goviel, Hail Knight II',
        'Gretch, Chimaera Mistress II',
        'Griflet, Falcon Knight',
        'Grim Executioner II',
        'Grimoire Beast II',
        'Hawke, Fleet Admiral II',
        'Hrimthurs the Blizzard II',
        'Hyacinth, the Death Dealer II',
        'Icemelt Dragon II',
        'Ignis Fatuus II',
        'Infested Peryton II',
        'Iron Golem II',
        'Jaguar Guardian II',
        'Kelaino, the Dark Cloud II',
        'Lenore, the False II',
        'Libuse, the Black Queen II',
        'Ma-Gu the Enlightened II',
        'Mammi, Spiritmancer II',
        'Mari the Witch',
        'Marsyas, Calamity Caller II',
        'Melusine the Witch II',
        'Merman Wave Rider II',
        'Mizuchi, the Maelstrom II',
        'Moloch, the Infernal Axe II',
        'Moren, Rime Mage II',
        'Ninurta, the Thunderclap II',
        'Phantom Assassin II',
        'Sir Bedwyr of the Garden II',
        'Slagh, Carnage Incarnate II',
        'Specter of the Mirror II',
        'Steamwork Dragon',
        'Sulima, Executioner II',
        'Tangata Manu',
        'Tepaxtl, Fatal Fang II',
        'Thor, God of Lightning II',
        'Twar, Ghost Archmage II',
        'Two-Headed Stormwyrm II',
        'Undead General, Hydarnes II',
        'Ushabti II',
        'Vucub Caquix, the Dark Wing II',
        'Wu Chang the Infernal II',
        'Yule Goat, the Blood-Stained II',
        'Yulia, Snakesage II'
    ],
    C: [
        'Adonis the Bard II',
        'Aegis, the Bulwark',
        'Ahab, the Colossal Anchor II',
        'Almase the Gelid II',
        'Alp, the Dead of Night II',
        'Alviss, the Dismantler II',
        'Amazon Warfist II',
        'Antiope of the Axe II',
        'Arachnaea the Divine II',
        'Argos II',
        'Artemisia Swiftfoot II',
        'Attis the Amazonite Warrior II',
        'Badrigo the Diamond Sword II',
        'Baklus of Viper Armor II',
        'Bare-Branch Treant II',
        'Beheading Scarecrow II',
        'Beguiling Succubus II',
        'Black Cat Knight II',
        'Bheara, Tree of Death II',
        'Boudica, the Dawn Chief II',
        'Brownies, the Uproarious II',
        'Buraq, the Mourning II',
        'Caim, the Dark Plume II',
        'Cat Sith Leopard Queen II',
        'Catoblepas Groundgazer II',
        'Celestial Kirin II',
        'Chanoir, the Crimson Scythe II',
        'Chikagoro, Master Samurai II',
        'Coco, Gorilla Bandit Chief II',
        'Culann, Raving Gravekeeper II',
        'Cursed Inugami II',
        'Cursed Pumpkin Golem II',
        'Dark Hrimthurs II',
        'Depraved Satyr II',
        'Dharva, the Shadowmoon II',
        'Diaochan the Bewitching II',
        'Diamond Guivre II',
        'Donga the Exterminator II',
        'Dovin, Bounty Mistress II',
        'Earl Cat Sidhe II',
        'Empusa the Alluring II',
        'Enkidu the Invincible II',
        'Enz Rumblefoot II',
        'Esmereldathe Cunning II',
        'Fafnir, Fire Dragon II',
        'Flamel, Evil-eyed Alchemist II',
        'Flauros, Duke of Leopards II',
        'Furiae, the Fury II',
        'Gazal the Emerald Arrow II',
        'Gazer, the Tyrant\'s Eye II',
        'Galahad, Drake Knight II',
        'Golad the Mighty II',
        'Golden Fur Gullinbursti II',
        'Gorgon II',
        'Granados, Lion King II',
        'Gregoire, Weaponmaster II',
        'Grendel the Cruel II',
        'Guerson, Thunder Mage II',
        'Hagen, Mad King II',
        'Haokah, the Darkthunder II',
        'Havers the Jade II',
        'Heavy Automaton II',
        'Hellfire Anzu II',
        'Hervor, the Cursed Blade II',
        'Hilde the Sapphire Talons II',
        'Hippelaphe Thrallsong II',
        'Hogni Ruinblade II',
        'Houdi, the Illusory Flame II',
        'Hydra II',
        'Iamek, the Thunderstroke II',
        'Iapetus the Earthquake II',
        'Ibicella, Slaughter II',
        'Ironstone Girtablilu II',
        'Isegrim, the Lone Wolf II',
        'Jeanne, Knight Templar II',
        'Katiria Nullblade II',
        'Kosche, the Scorching II',
        'Kua Fu, the Eclipse II',
        'Kuki, Pirate Busho II',
        'Lahmu, Snake King II',
        'Lailoken, Vile Magus II',
        'Lamassu the Merciful II',
        'Leon, Chaos Chanter II',
        'Li Zhi, the Tiger\'s Roar II',
        'Lia, Gladiator II',
        'Lilith, the Night Witch II',
        'Lindworm, the Black Rose II',
        'Lycaon, Wolf King II',
        'Macaca, the Headlong II',
        'Makalipon, Sacred Fruit II',
        'Master Zeku II',
        'Marcus, Blood Warrior II',
        'Maxe, the Ballista II',
        'Moh Shuvuu, the Dread Bride II',
        'Monos, Lesser Skull Ape',
        'Mordred, Drake Knight',
        'Mummy ++',
        'Mummy II ++',
        'Mystic Idol ++',
        'Mystic Idol II ++',
        'Naberius II',
        'Narluce, Steel Knight II',
        'Nessus, Centaur Gaoler II',
        'Nicola, Corpse Handler II',
        'Nidhogg, Ice Dragon II',
        'Nightmare Charger II',
        'Nine-tailed Fox II',
        'Nuadha, the Shining Blade II',
        'Oberon, Faerie King II',
        'Oedipus, Tragic King II',
        'Onyx Roc II',
        'Ogre Marrowwalki II',
        'Onra, Ogre of Darkness',
        'Okypete, the Night Breeze II',
        'Orthros',
        'Pabilsag Venomclaw II',
        'Pan of the Flute II',
        'Paracelsus, Venomdagger II',
        'Pazuzu, the Fiery One II',
        'Peluda the Poison Flame II',
        'Pendragon, the Scourge II',
        'Petsuchos Executioner II',
        'Phineus, the Augur King II',
        'Pouliquen, Archibishop II',
        'Prince Asterios II',
        'Princeps, Angel of Doom II',
        'Prowling Keeper II',
        'Queen Echidna II',
        'Qiong Qi, Man Eater II',
        'Randolph the Crazed II',
        'Ran, Phantom Killer II',
        'Roksva, Jewel Master II',
        'Rudolph, Spirit Warrior II',
        'Santa, Bringer of Death II',
        'Scylla II',
        'Seiten Taisei II',
        'Set, the Shadowstorm II',
        'Sevia the Keen II',
        'Shackled White Wyrm',
        'Sigiled Ghost Knight II',
        'Sir Kay the Golden Bat II',
        'Sir Morholt, Everduelist II',
        'Sphinx, Deathwatcher II',
        'Skrimsl, Crystal Eternal II',
        'Sun-God Lugh II',
        'Surtr the Ashen II',
        'Suzuka, Bandit Chief II',
        'Talos',
        'Tametomo, Master Archer II',
        'Taromaiti, Depraved Queen II',
        'Telida, the Goldback II',
        'Tlahuizcal, the Calamity II',
        'Tulok, Icebreaker II',
        'Tuniq, Guardian Colossus II',
        'Twintail Sandwalker II',
        'Unbound Gargoyle II',
        'Unbound Gem Golem II',
        'Unicorn, Spirit Eater II',
        'Uorko Maneater II',
        'Vengeful Rattlebones II',
        'Vepar, the Perpetual Night II',
        'Wailing Banshee II',
        'Wledic, Guard Captain II',
        'Wynde, Dragonslayer II',
        'Xaphan, the Shadow Wing II',
        'Xin Lon, The Blue Dragon II',
        'Yale, Avatar of the Forest II',
        'Zabbak the Eight-Sickles II',
        'Ziraiya, Master Ninja II',
        'Ziz, Wings Divine II',
        'Zombie Dragon II',
        'Zorg, the Cruncher II'
    ]
};